import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Spinner, Button } from '@markcards/ui';
import { EmptyState } from '../../_shared/EmptyState';
import { inputQueryOptions, confirmCard, rejectCard } from '../../api/input';
import type { InputCard } from '@markcards/types';

function InputCardItem({ card, onDone }: { card: InputCard; onDone: () => void }) {
  const [editedMarkdown, setEditedMarkdown] = useState(card.rawMarkdown);
  const [loading, setLoading] = useState(false);

  const handleConfirm = async () => {
    setLoading(true);
    try {
      await confirmCard(card.id, editedMarkdown);
      onDone();
    } finally {
      setLoading(false);
    }
  };

  const handleReject = async () => {
    setLoading(true);
    try {
      await rejectCard(card.id);
      onDone();
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="border border-border p-4 flex flex-col gap-3 bg-card">
      <div className="text-xs text-muted-foreground font-mono">{card.destPath}</div>
      <textarea
        className="w-full font-mono text-sm bg-background text-foreground border border-border p-2 resize-y min-h-[100px] focus:outline-none focus:border-foreground"
        value={editedMarkdown}
        onChange={e => setEditedMarkdown(e.target.value)}
        disabled={loading}
      />
      <div className="flex gap-2">
        <Button variant="primary" size="sm" onClick={handleConfirm} disabled={loading}>
          Confirm
        </Button>
        <Button variant="secondary" size="sm" onClick={handleReject} disabled={loading}>
          Reject
        </Button>
      </div>
    </div>
  );
}

export function InputPage() {
  const { data, isLoading, error } = useQuery(inputQueryOptions);
  const queryClient = useQueryClient();

  const handleDone = () => {
    queryClient.invalidateQueries({ queryKey: ['input'] });
  };

  if (isLoading) {
    return (
      <div className="flex justify-center py-20">
        <Spinner size="lg" />
      </div>
    );
  }

  if (error) {
    return <EmptyState title="Failed to load input cards" description={error.message} />;
  }

  const cards = data?.cards ?? [];

  if (!cards.length) {
    return <EmptyState title="No input cards" description="Cards generated by the Telegram bot will appear here for review." />;
  }

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
      {cards.map(card => (
        <InputCardItem key={card.id} card={card} onDone={handleDone} />
      ))}
    </div>
  );
}
