import { useState } from 'react';
import { marked, Renderer } from 'marked';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Spinner, Button, EditableCardSummary } from '@markcards/ui';
import { EmptyState } from '../../_shared/EmptyState';
import { inputQueryOptions, confirmCard, rejectCard } from '../../api/input';
import type { RenderedInputCard } from '../../api/input';

function renderMarkdown(raw: string, imageBaseUrl?: string): string {
  const renderer = new Renderer();
  if (imageBaseUrl) {
    renderer.image = ({ href, title, text }) => {
      const src = href && !href.startsWith('http') && !href.startsWith('/')
        ? `${imageBaseUrl}/${href}`
        : href;
      return `<img src="${src}" alt="${text}"${title ? ` title="${title}"` : ''}>`;
    };
  }
  return marked.parse(raw, { renderer }) as string;
}

function parseAndRender(rawMarkdown: string, imageBaseUrl?: string): { promptHtml: string; revealHtml: string } {
  const text = rawMarkdown.trim();

  const clozeMatch = text.match(/^C:\s*([\s\S]+)/);
  if (clozeMatch) {
    const template = clozeMatch[1].trim();
    const prompt = template.replace(/\[([^\]]+)\]/g, '_____');
    return {
      promptHtml: renderMarkdown(prompt, imageBaseUrl),
      revealHtml: renderMarkdown(template, imageBaseUrl),
    };
  }

  const qMatch = text.match(/^Q:\s*([\s\S]*?)(?=\nA:)/);
  const aMatch = text.match(/\nA:\s*([\s\S]*?)$/);
  if (qMatch) {
    return {
      promptHtml: renderMarkdown(qMatch[1].trim(), imageBaseUrl),
      revealHtml: renderMarkdown(aMatch ? aMatch[1].trim() : '', imageBaseUrl),
    };
  }

  return {
    promptHtml: renderMarkdown(text, imageBaseUrl),
    revealHtml: '',
  };
}

function InputCardItem({ card, onDone }: { card: RenderedInputCard; onDone: () => void }) {
  const [editedMarkdown, setEditedMarkdown] = useState(card.rawMarkdown);
  const [loading, setLoading] = useState(false);

  const { promptHtml, revealHtml } = parseAndRender(editedMarkdown, card.imageBaseUrl);

  const handleConfirm = async () => {
    setLoading(true);
    try {
      await confirmCard(card.id, editedMarkdown);
      onDone();
    } finally {
      setLoading(false);
    }
  };

  const handleReject = async () => {
    setLoading(true);
    try {
      await rejectCard(card.id);
      onDone();
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="border border-border p-4 flex flex-col gap-3 bg-card">
      <div className="text-xs text-muted-foreground font-mono">{card.destPath}</div>
      <EditableCardSummary
        promptHtml={promptHtml}
        revealHtml={revealHtml}
        rawMarkdown={editedMarkdown}
        onMarkdownChange={setEditedMarkdown}
      />
      <div className="flex gap-2">
        <Button variant="primary" size="sm" onClick={handleConfirm} disabled={loading}>
          Confirm
        </Button>
        <Button variant="secondary" size="sm" onClick={handleReject} disabled={loading}>
          Reject
        </Button>
      </div>
    </div>
  );
}

export function InputPage() {
  const { data, isLoading, error } = useQuery(inputQueryOptions);
  const queryClient = useQueryClient();

  const handleDone = () => {
    queryClient.invalidateQueries({ queryKey: ['input'] });
  };

  if (isLoading) {
    return (
      <div className="flex justify-center py-20">
        <Spinner size="lg" />
      </div>
    );
  }

  if (error) {
    return <EmptyState title="Failed to load input cards" description={error.message} />;
  }

  const cards = data?.cards ?? [];

  if (!cards.length) {
    return <EmptyState title="No input cards" description="Cards generated by the Telegram bot will appear here for review." />;
  }

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
      {cards.map(card => (
        <InputCardItem key={card.id} card={card} onDone={handleDone} />
      ))}
    </div>
  );
}
